### ISSUE TITLE
Error in documentation or bug?

### ISSUE THREAD

**Issue by phochste** [LibreCat/Catmandu-DBI#11]
The example doesn't work:

    catmandu import JSON to DBI --data_source SQLite:mydb.sqlite < data.json

Works with

    catmandu import JSON to DBI --data_source DBI:SQLite:mydb.sqlite < data.json

The documentation for the constuctor tells it should work without DBI

    Create a new Catmandu::Store::DBI store using a DBI $data_source. The prefix "DBI:" is added automatically if needed.

Tested with Catmandu-DBI-0.0504

**Comment by phochste** [comment]
DBI:SQLite:mydb.sqlite is also advertised in the core Catmandu documentation . So I prefer this prefix not automatically added (or it should brake existing code)

**Comment by nicolasfranck** [comment]
Thanks for reporting this. A fix is added to the branch dev.
