### ISSUE TITLE
MYMETA must not be included

### ISSUE THREAD

**Issue by chorny** [LibreCat/Catmandu-DBI#12]
Your distribution (NJFRANCK/Catmandu-DBI-0.0506.tar.gz) contains files MYMETA.json/MYMETA.yml. These files must not be included into distribution - they are generated when installing.
See http://weblog.bulknews.net/post/44251476706/stop-shipping-mymeta-to-cpan

P.S. If this report is for an old version, please delete old indexed versions mentioned here: http://cpanold.chorny.net/?a=NJFRANCK and contact me.
P.P.S. This report was generated automatically.

**Comment by nicolasfranck** [comment]
Thanks for noticing this. Update is on the way
