### ISSUE TITLE
Support a basic search on mapped fields

### ISSUE THREAD

**Issue by phochste** [LibreCat/Catmandu-DBI#14]
If I have a store like:

```(perl)
my $store = Catmandu::Store::DBI->new(
    data_source => 'DBI:mysql:database=test',
    bags => {
        # books table
        books => {
            mapping => {
                # these keys will be directly mapped to columns
                # all other keys will be serialized in the data column
                title => {type => 'string', required => 1, column => 'book_title'},
                isbn => {type => 'string', unique => 1},
                authors => {type => 'string', array => 1}
            }
        }
    }
);
```

I would like to do a :

```(perl)
my $hits = $store->bags('books')->search("title = 'DNA'");
```

This documentation mentions a reference to Catmandu::Searchable anyway.

**Comment by nicolasfranck** [comment]
That's already possible using the "select" syntax:

```
my $selector = $bag->select( title => "DNA" );
my $total = $selector->count();
my $hits = $selector->slice(0,100);
```

Catmandu::Store::DBI::Bag overrides the method "select":

* when the search field is known, it creates a real sql query
* when not, the super method "select" takes over, which means: iterating over the whole bag,
and filtering on the given pairs.

**Comment by vpeil** [comment]
should be included in POD, if not already there!

**Comment by phochste** [comment]
The POD is confusing. This is option is not described and even there is a suggestion in the POD that this store is a  Catmandu::Searchable,

**Comment by nicolasfranck** [comment]
It isn't a Catmandu::Searchable. Those require a method "search". It just has an speed enhancement for the method "select". But you're right, it should be documented that you can use the "select" method safely without worrying about Catmandu iterating over the whole bag.

**Comment by nicolasfranck** [comment]
I've added some documentation in this branch:

https://github.com/LibreCat/Catmandu-DBI/blob/document_iterator/lib/Catmandu/Store/DBI/Bag.pm

Does this provide enough information?
