### ISSUE TITLE
PostgreSQL handler should support the native JSONB types instead of storing in a BLOB

### ISSUE THREAD

**Issue by phochste** [LibreCat/Catmandu-DBI#16]
PostgreSQL has native support for JSON : https://www.postgresql.org/docs/9.4/static/datatype-json.html This should be the preferred way to store Catmandu records.

**Comment by nics** [comment]
Only in recent versions. We need a reliable way to test support for this.

**Comment by nicolasfranck** [comment]
Something like:
```
if ( $dbh->{pg_server_version} < 90400 ) {

}
```
cf. https://huntingbears.nl/2015/01/18/postgresql-9-4s-jsonb-and-perl-dbdpg/

**Comment by nicolasfranck** [comment]
https://github.com/LibreCat/Catmandu-DBI/pull/24

**Comment by nics** [comment]
Pg handler now this as the 'json' type
