### ISSUE TITLE
DBI iterator starts fast, but slows down afterwards

### ISSUE THREAD

**Issue by nicolasfranck** [LibreCat/Catmandu-DBI#17]
The reason for this is the generator in Catmandu::Store::DBI::Iterator,
that fetches the records in batches: for every batch a query is executed,
using "order by id", "offset" and "limit". This means that the underlying
dbi system has to jump further every time it is accessed.

Better to cache the cursor

**Comment by nicolasfranck** [comment]
https://github.com/LibreCat/Catmandu-DBI/pull/18

**Comment by nics** [comment]
merged in bb193400eae25d0778a47c08e0821230a4b47c59, released as 0.06
