### ISSUE TITLE
Support custom ORDER field

### ISSUE THREAD

**Issue by phochste** [LibreCat/Catmandu-DBI#19]
In the current implementation the DBI Iterator is ordered on `_id`. Make this order configurable (and maybe also ignore order in some cases)

**Comment by nicolasfranck** [comment]
@nics : now the records aren't fetched anymore in batches, leaving out the order should be possible, I think?

**Comment by nics** [comment]
yes that's correct

**Comment by nics** [comment]
resolved by #27
