### ISSUE TITLE
custom mapped text fields do not support utf-8

### ISSUE THREAD

**Issue by nicolasfranck** [LibreCat/Catmandu-DBI#26]
The reason for this is that the database encoding is  set to sql_ascii by default.
Insertion fails with "wide character ..".

This does not happen for the field "data" where the type is "bytea", and the data
is accepted as-is.

**Comment by nics** [comment]
utf-8 columns are assumed, the pod now describes the limitations (58ef8b1444a6fcc936615f3515c7d7f47d95527a)
