### ISSUE TITLE
Make it configurable to set the encoding of the database

### ISSUE THREAD

**Issue by phochste** [LibreCat/Catmandu-DBI#29]
In a previous version of Catmandu::DBI the default encoding of the SQLite databases was ascii now it is standaard uncode. This has the effect that old databases can't be read with Catmandu tools when UTF-8 encoded data was stored in the database.

```
Oops! malformed UTF-8 character in JSON string, at character offset 138 (before "\x{fffd}enri Constan...") at /opt/librecat/local/lib/perl5/Catmandu/Serializer/json.pm line 16.
```

**Comment by nics** [comment]
utf-8 columns are assumed, the pod now describes the limitations (58ef8b1444a6fcc936615f3515c7d7f47d95527a)
